default_context:
    repo_name: "minimal_repo"
    project_name: "project_name"
    project_description: "description"
    author_name: "author_name"
    project_structure: "simple"
    package_manager: "pip"
    python_version: "3.12"
    use_databricks: "no"
    use_airflow: "no"
    use_terraform: "no"
    use_mlflow: "no"
    enable_drift_monitoring: "no"
    enable_etl: "no"
    open_source_license: "MIT"